AWSTemplateFormatVersion: "2010-09-09"

Description: >
  Datadog Lambda Remote Instrumentation App

# All version values except L12 are double-quoted on purpose since publish.sh is searching for
# version string and replace the value with new version. All other version values should be
# double-quoted.
Mappings:
  Constants:
    DatadogRemoteInstrumentDemoApp:
      Version: 0.1.0

Parameters:
  DdApiKey:
    Type: String
    Description: >-
      The Datadog API key, which can be found from the APIs page
      (/organization-settings/api-keys).
    NoEcho: true
  DdSite:
    Type: String
    Default: datadoghq.com
    Description: >-
      Define your Datadog Site to send data to. Possible values are
      `datadoghq.com`, `datadoghq.eu`, `us3.datadoghq.com`, `us5.datadoghq.com`
      and `ddog-gov.com`.
    AllowedPattern: .+
    ConstraintDescription: DdSite is required
  StackName:
    Type: String
    Default: datadog-remote-instrument
    Description: >-
      Define the Lambda fulnction name which is instrumenting the other Lambda functions.
  InstrumenterFunctionName:
    Type: String
    Default: datadog-remote-instrumenter
    Description: >-
      Define the Lambda fulnction name which is instrumenting the other Lambda functions.
  BucketName:
    Type: String
    Default: datadog-serverless-instrumentation-5
  TrailName:
    Type: String
    Default: datadog-serverless-instrumentation-trail
  DdAwsAccountNumber:
    Type: String
    Default: '425362996713'
  AllowList:
    Type: String
    Default: test-auto-instrument-node,test-auto-instrument-another-node,test-auto-instrument-does-not-exist,test-auto-instrument-python,test-auto-instrument-to-be-uninstrumented
  TagRule:
    Type: String
    Default: DD_REMOTE_INSTRUMENT_ENABLED:true
  DenyList:
    Type: String
    Default: test-auto-instrument-to-be-uninstrumented
  DdExtensionLayerVersion:
    Type: String
    Default: '50'
  DdPythonLayerVersion:
    Type: String
    Default: '70'
  DdNodeLayerVersion:
    Type: String
    Default: '100'
#  DdJavaLayerVersion:
#    Type: String
#    Default: ''
#  DdDotnetLayerVersion:
#    Type: String
#    Default: ''
#  DdRubyLayerVersion:
#    Type: String
#    Default: ''

Resources:
  CloudFormationLifeCycle:
    Type: 'AWS::CloudFormation::CustomResource'
    Version: '1.0'
    Properties:
      ServiceToken: !GetAtt LambdaFunction.Arn
      FunctionName: !Ref InstrumenterFunctionName
  LambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: !Ref InstrumenterFunctionName
      Architectures:
      - arm64
      Runtime: nodejs20.x
      Timeout: 840
      MemorySize: 512
      Role: !GetAtt LambdaExecutionRole.Arn
      Handler: /opt/nodejs/node_modules/datadog-lambda-js/handler.handler
      Layers:
        - !Sub 'arn:aws:lambda:${AWS::Region}:464622532012:layer:Datadog-Extension-ARM:50'
        - !Sub 'arn:aws:lambda:${AWS::Region}:464622532012:layer:Datadog-Node20-x:99'
        - !Sub 'arn:aws:lambda:${AWS::Region}:464622532012:layer:Datadog-Serverless-Remote-Instrumentation-ARM:1'
#        - !Sub 'arn:aws:lambda:${AWS::Region}:425362996713:layer:Datadog-Serverless-Remote-Instrumentation-ARM:6'
      Environment:
        Variables:
          DD_LAMBDA_HANDLER: index.handler
          DD_TRACE_ENABLED: true
          DD_API_KEY: !Ref DdApiKey
          DD_LOG_LEVEL: DEBUG
          DD_TRACE_DEBUG: false
          DD_SERVICE: Datadog-Instrument
          DD_ENV: dev
          DD_VERSION: 0.1.0
          DD_SITE: !Ref DdSite
          DD_AWS_ACCOUNT_NUMBER: !Ref DdAwsAccountNumber
          AllowList: !Ref AllowList
          TagRule: !Ref TagRule
          DenyList: !Ref DenyList
          DD_EXTENSION_LAYER_VERSION: !Ref DdExtensionLayerVersion
          DD_PYTHON_LAYER_VERSION: !Ref DdPythonLayerVersion
          DD_NODE_LAYER_VERSION: !Ref DdNodeLayerVersion
#          DD_JAVA_LAYER_VERSION: !Ref DdJavaLayerVersion
#          DD_DOTNET_LAYER_VERSION: !Ref DdDotnetLayerVersion
#          DD_RUBY_LAYER_VERSION: !Ref DdRubyLayerVersion
      Tags:
        - Key: "dd_serverless_service"
          Value: "remote_instrumenter"
      Code:
        ZipFile: |
          INJECT_ENTRY_FUNCTION_CODE_PLACEHOLDER

  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      Path: "/"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogStream
            - logs:CreateLogGroup
            - logs:PutLogEvents
            Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*
          - Effect: Allow
            Action:
              - lambda:InvokeFunction
              - lambda:GetFunction
              - lambda:UpdateFunctionConfiguration
              - lambda:TagResource
              - lambda:UntagResource
            Resource: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:*
          - Effect: Allow
            Action:
              - lambda:GetLayerVersion
            Resource: !Sub arn:aws:lambda:${AWS::Region}:464622532012:layer:*
          - Effect: Allow
            Action:
              - lambda:ListTags
            Resource: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:*
          - Effect: Allow
            Action:
              - tag:GetResources
              - tag:TagResources
              - tag:UntagResources
            Resource: '*'
#            Resource: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:*  # doesn't work
#            Resource: 'arn:aws:lambda:*'  # doesn't work

  CloudTrail:
    Type: AWS::CloudTrail::Trail
    DependsOn:
      - S3Bucket
    Properties:
      S3BucketName: !Ref BucketName
      IsLogging: true
      TrailName: !Ref TrailName
      EnableLogFileValidation: false
      IncludeGlobalServiceEvents: false
      IsMultiRegionTrail: false
      Tags:
        - Key: "env"
          Value: "dev"
      AdvancedEventSelectors:
        - Name: "Lambda Management Events"
          FieldSelectors:
            - Field: "eventCategory"
              Equals: [ "Management" ]
            - Field: "eventSource"
              NotEquals:
                - kms.amazonaws.com
                - rdsdata.amazonaws.com
            - Field: "readOnly"
              Equals:
                - "false"
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      BucketName: !Ref BucketName
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref BucketName
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AWSCloudTrailAclCheck20150319
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !Sub "arn:aws:s3:::${BucketName}"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudtrail:${AWS::Region}:${AWS::AccountId}:trail/${TrailName}"
          - Sid: AWSCloudTrailWrite20150319
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub "arn:aws:s3:::${BucketName}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudtrail:${AWS::Region}:${AWS::AccountId}:trail/${TrailName}"
                s3:x-amz-acl: bucket-owner-full-control
  LambdaEventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "EventRule for piping lambda management events to Datadog lambda instrumenter"
      EventPattern:
        source:
          - aws.lambda
        detail:
          eventSource:
            - lambda.amazonaws.com
      State: "ENABLED"
      Targets:
        - Arn: !GetAtt LambdaFunction.Arn
          Id: "DatadogInstrumentingLambdaTarget"
  LambdaTagResourceEventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "EventRule for piping lambda TagResource20170331v2 management events to Datadog lambda instrumenter"
      EventPattern:
        source:
          - aws.lambda
        detail:
          eventSource:
            - lambda.amazonaws.com
      State: "ENABLED"
      Targets:
        - Arn: !GetAtt LambdaFunction.Arn
          Id: "DatadogInstrumentingLambdaTarget"
  StackUpdateEventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "EventRule for piping stack update management events to Datadog lambda instrumenter"
      State: "ENABLED"
      Targets:
        - Arn: !GetAtt LambdaFunction.Arn
          Id: "DatadogInstrumentingLambdaTarget"
      EventPattern:
        source:
          - aws.cloudformation
        detail-type:
          - CloudFormation Stack Status Change
        resources:
#          - wildcard: !Sub "arn:aws:cloudformation:*:*:stack/${StackName}*/*"  -> does not work
          # Hardcoded stack name so the customer cannot change their stack name until RC integration is released
          - wildcard: arn:aws:cloudformation:*:*:stack/datadog-remote-instrument*/*
        detail:
          status-details:
            status:
              - UPDATE_COMPLETE
  EventBridgeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref InstrumenterFunctionName
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt LambdaEventRule.Arn
  EventBridgeLambdaPermission2:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref InstrumenterFunctionName
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt StackUpdateEventRule.Arn
