// This file is generated. Do not edit it directly.

export const RUNTIME_CATALOG = [
  {
    runtime: "dotnet10",
    family: "dotnet",
    tracerLayerPrefix: "dd-trace-dotnet",
    configField: "dotnetLayerVersion",
    jsonConfigField: "dotnet_layer_version",
  },
  {
    runtime: "dotnet6",
    family: "dotnet",
    tracerLayerPrefix: "dd-trace-dotnet",
    configField: "dotnetLayerVersion",
    jsonConfigField: "dotnet_layer_version",
  },
  {
    runtime: "dotnet8",
    family: "dotnet",
    tracerLayerPrefix: "dd-trace-dotnet",
    configField: "dotnetLayerVersion",
    jsonConfigField: "dotnet_layer_version",
  },
  {
    runtime: "java11",
    family: "java",
    tracerLayerPrefix: "dd-trace-java",
    configField: "javaLayerVersion",
    jsonConfigField: "java_layer_version",
  },
  {
    runtime: "java17",
    family: "java",
    tracerLayerPrefix: "dd-trace-java",
    configField: "javaLayerVersion",
    jsonConfigField: "java_layer_version",
  },
  {
    runtime: "java21",
    family: "java",
    tracerLayerPrefix: "dd-trace-java",
    configField: "javaLayerVersion",
    jsonConfigField: "java_layer_version",
  },
  {
    runtime: "java25",
    family: "java",
    tracerLayerPrefix: "dd-trace-java",
    configField: "javaLayerVersion",
    jsonConfigField: "java_layer_version",
  },
  {
    runtime: "java8.al2",
    family: "java",
    tracerLayerPrefix: "dd-trace-java",
    configField: "javaLayerVersion",
    jsonConfigField: "java_layer_version",
  },
  {
    runtime: "nodejs18.x",
    family: "node",
    tracerLayerPrefix: "Datadog-Node",
    configField: "nodeLayerVersion",
    jsonConfigField: "node_layer_version",
  },
  {
    runtime: "nodejs20.x",
    family: "node",
    tracerLayerPrefix: "Datadog-Node",
    configField: "nodeLayerVersion",
    jsonConfigField: "node_layer_version",
  },
  {
    runtime: "nodejs22.x",
    family: "node",
    tracerLayerPrefix: "Datadog-Node",
    configField: "nodeLayerVersion",
    jsonConfigField: "node_layer_version",
  },
  {
    runtime: "nodejs24.x",
    family: "node",
    tracerLayerPrefix: "Datadog-Node",
    configField: "nodeLayerVersion",
    jsonConfigField: "node_layer_version",
  },
  {
    runtime: "provided.al2",
    family: "custom",
  },
  {
    runtime: "provided.al2023",
    family: "custom",
  },
  {
    runtime: "python3.10",
    family: "python",
    tracerLayerPrefix: "Datadog-Python",
    configField: "pythonLayerVersion",
    jsonConfigField: "python_layer_version",
  },
  {
    runtime: "python3.11",
    family: "python",
    tracerLayerPrefix: "Datadog-Python",
    configField: "pythonLayerVersion",
    jsonConfigField: "python_layer_version",
  },
  {
    runtime: "python3.12",
    family: "python",
    tracerLayerPrefix: "Datadog-Python",
    configField: "pythonLayerVersion",
    jsonConfigField: "python_layer_version",
  },
  {
    runtime: "python3.13",
    family: "python",
    tracerLayerPrefix: "Datadog-Python",
    configField: "pythonLayerVersion",
    jsonConfigField: "python_layer_version",
  },
  {
    runtime: "python3.14",
    family: "python",
    tracerLayerPrefix: "Datadog-Python",
    configField: "pythonLayerVersion",
    jsonConfigField: "python_layer_version",
  },
  {
    runtime: "python3.8",
    family: "python",
    tracerLayerPrefix: "Datadog-Python",
    configField: "pythonLayerVersion",
    jsonConfigField: "python_layer_version",
  },
  {
    runtime: "python3.9",
    family: "python",
    tracerLayerPrefix: "Datadog-Python",
    configField: "pythonLayerVersion",
    jsonConfigField: "python_layer_version",
  },
  {
    runtime: "ruby3.2",
    family: "ruby",
    tracerLayerPrefix: "Datadog-Ruby",
    configField: "rubyLayerVersion",
    jsonConfigField: "ruby_layer_version",
  },
  {
    runtime: "ruby3.3",
    family: "ruby",
    tracerLayerPrefix: "Datadog-Ruby",
    configField: "rubyLayerVersion",
    jsonConfigField: "ruby_layer_version",
  },
  {
    runtime: "ruby3.4",
    family: "ruby",
    tracerLayerPrefix: "Datadog-Ruby",
    configField: "rubyLayerVersion",
    jsonConfigField: "ruby_layer_version",
  },
  {
    runtime: "ruby4.0",
    family: "ruby",
    tracerLayerPrefix: "Datadog-Ruby",
    configField: "rubyLayerVersion",
    jsonConfigField: "ruby_layer_version",
  },
] as const;
