name: lint
permissions:
  contents: read

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b

      - name: Set up Node 20
        uses: actions/setup-node@9ced9a43a244f3ac94f13bfd896db8c8f30da67a
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Run linter
        run: yarn lint
