name: Unit Tests
permissions:
  contents: read

on: [pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Run Tests
        run: yarn test
