name: Update Self Monitoring
permissions:
  contents: read
  id-token: write
env:
  RUNNING_IN_GITHUB_ACTION: true
  SELF_MONITORING: true
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: "ap-south-1"
  PR_TITLE: ${{ github.event.pull_request.title }}

on:
  push:
    branches: [prod]

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b

      - name: Set up Node
        uses: actions/setup-node@9ced9a43a244f3ac94f13bfd896db8c8f30da67a
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Setup Infrastructure
        run: yarn integ-test-setup
